#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-walkthrough/rehearsal.md"

usage() {
  cat <<'USAGE'
Usage: scripts/check-phase2-rust-walkthrough-rehearsal.sh [--output <path>]

Options:
  --output <md>   Output markdown report path
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-walkthrough/rehearsal.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

OUT_DIR="$(dirname "$OUTPUT")"
REPORT_STEM="$(basename "$OUTPUT" .md)"
RUN_DIR="$OUT_DIR/$REPORT_STEM"
LOG_DIR="$RUN_DIR/logs"
SANDBOX="$RUN_DIR/sandbox"
MANIFEST="$RUN_DIR/manifest.toml"
mkdir -p "$LOG_DIR" "$SANDBOX/fixtures"

WASM_PATH="$ROOT/apps/layer36-cat/target/wasm32-wasip1/release/layer36_cat.wasm"
LAYER36="$ROOT/target/debug/layer36"
HELLO_FILE="$SANDBOX/fixtures/hello.txt"
printf 'hello from Layer36\n' >"$HELLO_FILE"

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"

status_rows=""
overall=0

run_step() {
  name="$1"
  expected="$2"
  log_file="$3"
  shift 3

  if "$@" >"$log_file" 2>&1; then
    code=0
    result="passed"
  else
    code=$?
    result="failed"
    overall=1
  fi

  status_rows="${status_rows}| ${name} | ${expected} | ${code} | ${result} | ${log_file} |
"
}

run_step "Tool check" "doctor exits 0" "$LOG_DIR/doctor.log" \
  cargo run -p layer36-cli -- doctor

run_step "Build CLI" "debug CLI exists" "$LOG_DIR/build-cli.log" \
  cargo build -p layer36-cli

run_step "Build cat component" "wasm component exists" "$LOG_DIR/build-cat-component.log" \
  scripts/build-layer36-cat-component.sh

if [ ! -f "$WASM_PATH" ]; then
  printf 'expected wasm not found: %s\n' "$WASM_PATH" >"$LOG_DIR/build-cat-component-missing.log"
  status_rows="${status_rows}| Build cat component artifact | wasm exists at expected path | 1 | failed | $LOG_DIR/build-cat-component-missing.log |
"
  overall=1
else
  status_rows="${status_rows}| Build cat component artifact | wasm exists at expected path | 0 | passed | $WASM_PATH |
"
fi

run_step "Generate manifest" "manifest init exits 0" "$LOG_DIR/manifest-init.log" \
  cargo run -p layer36-cli -- manifest init \
    --id dev.layer36.walkthrough-rehearsal \
    --name layer36-walkthrough-rehearsal \
    --entry "$WASM_PATH" \
    --cap io.args \
    --cap io.stdout \
    --cap io.stderr \
    --cap 'fs.read:./fixtures/**' \
    --output "$MANIFEST" \
    --force

run_step "Explain manifest" "manifest explain exits 0" "$LOG_DIR/manifest-explain.log" \
  cargo run -p layer36-cli -- manifest explain "$MANIFEST"

GRANTED_STDOUT="$LOG_DIR/granted.stdout"
GRANTED_STDERR="$LOG_DIR/granted.stderr"
if "$LAYER36" run \
  --manifest "$MANIFEST" \
  --sandbox-root "$SANDBOX" \
  --auto-grant \
  "$WASM_PATH" \
  -- ./fixtures/hello.txt >"$GRANTED_STDOUT" 2>"$GRANTED_STDERR"; then
  if cmp -s "$GRANTED_STDOUT" "$HELLO_FILE"; then
    status_rows="${status_rows}| Granted run | app prints fixture text | 0 | passed | $GRANTED_STDOUT |
"
  else
    status_rows="${status_rows}| Granted run | app prints fixture text | 1 | failed | $GRANTED_STDOUT |
"
    overall=1
  fi
else
  code=$?
  status_rows="${status_rows}| Granted run | app prints fixture text | ${code} | failed | $GRANTED_STDERR |
"
  overall=1
fi

DENIED_STDOUT="$LOG_DIR/denied.stdout"
DENIED_STDERR="$LOG_DIR/denied.stderr"
if printf '' | "$LAYER36" run \
  --manifest "$MANIFEST" \
  --sandbox-root "$SANDBOX" \
  "$WASM_PATH" \
  -- ./fixtures/hello.txt >"$DENIED_STDOUT" 2>"$DENIED_STDERR"; then
  status_rows="${status_rows}| Denied run | missing grant exits non-zero | 0 | failed | $DENIED_STDOUT |
"
  overall=1
else
  code=$?
  if grep -E "missing|required|capabilit|permission" "$DENIED_STDERR" >/dev/null 2>&1; then
    status_rows="${status_rows}| Denied run | missing grant exits before native file access | ${code} | passed | $DENIED_STDERR |
"
  else
    status_rows="${status_rows}| Denied run | missing grant explains missing capability | ${code} | failed | $DENIED_STDERR |
"
    overall=1
  fi
fi

{
  echo "# Phase 2 Rust Walkthrough Rehearsal"
  echo
  echo "This file is generated by \`scripts/check-phase2-rust-walkthrough-rehearsal.sh\`."
  echo
  echo "It is not the outside walkthrough evidence. It is a local check that the"
  echo "current Rust walkthrough commands still work before asking a reviewer to run"
  echo "them."
  echo
  echo "## Metadata"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Manifest: \`$MANIFEST\`"
  echo "- Sandbox: \`$SANDBOX\`"
  echo "- Component: \`$WASM_PATH\`"
  echo
  echo "## Step Results"
  echo
  echo "| Step | Expected result | Exit code | Result | Log |"
  echo "|---|---|---:|---|---|"
  printf '%s' "$status_rows"
  echo
  echo "## Result"
  echo
  if [ "$overall" -eq 0 ]; then
    echo "The local rehearsal passed."
  else
    echo "The local rehearsal failed. Check the step logs above."
  fi
} >"$OUTPUT"

echo "wrote $OUTPUT"
exit "$overall"
