#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-ucap-evidence/ucap-enforcement-evidence.md"
STRICT="${LAYER36_UCAP_EVIDENCE_STRICT:-0}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-ucap-evidence.sh [--strict] [--output <path>]

Options:
  --strict         Exit non-zero when any evidence step fails
  --output <path>  Output markdown file path

Environment:
  LAYER36_UCAP_EVIDENCE_STRICT   1 to exit non-zero when any step fails
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-ucap-evidence/ucap-enforcement-evidence.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-ucap-evidence/.tmp"
mkdir -p "$TMP_DIR"

RUNTIME_LOG="$TMP_DIR/runtime.log"
DISPATCHER_LOG="$TMP_DIR/dispatcher.log"
CAT_LOG="$TMP_DIR/cat.log"
CURL_LOG="$TMP_DIR/curl.log"
MANIFEST_LOG="$TMP_DIR/manifest.log"
LANGUAGE_LOG="$TMP_DIR/language.log"

if cargo test -p layer36-runtime uapi::tests::non_default_capabilities_are_denied_by_default_policy -- --exact >"$RUNTIME_LOG" 2>&1; then
  RUNTIME_CODE=0
else
  RUNTIME_CODE=$?
fi

if cargo test -p layer36-runtime uapi_dispatch::tests::dispatcher_denies_all_non_default_boundaries_before_adapter -- --exact >"$DISPATCHER_LOG" 2>&1; then
  DISPATCHER_CODE=0
else
  DISPATCHER_CODE=$?
fi

if cargo test -p layer36-cli --test cli configured_layer36_cat_component_denies_missing_file_grant -- --exact >"$CAT_LOG" 2>&1; then
  CAT_CODE=0
else
  CAT_CODE=$?
fi

if cargo test -p layer36-cli --test cli configured_layer36_curl_component_denies_missing_net_grant -- --exact >"$CURL_LOG" 2>&1; then
  CURL_CODE=0
else
  CURL_CODE=$?
fi

if cargo test -p layer36-cli --test cli run_with_manifest_denies_missing_required_capability -- --exact >"$MANIFEST_LOG" 2>&1; then
  MANIFEST_CODE=0
else
  MANIFEST_CODE=$?
fi

if cargo test -p layer36-cli --test cli language_variants_curl_permission_denied_matches_rust_go_ts -- --exact >"$LANGUAGE_LOG" 2>&1; then
  LANGUAGE_CODE=0
else
  LANGUAGE_CODE=$?
fi

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  else
    printf 'failed'
  fi
}

{
  echo "# Phase 2 UCap Enforcement Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-ucap-evidence.sh\`."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| Runtime UCap deny matrix (\`cargo test -p layer36-runtime uapi::tests::non_default_capabilities_are_denied_by_default_policy -- --exact\`) | $RUNTIME_CODE | $(result_of "$RUNTIME_CODE") |"
  echo "| Dispatcher deny-before-adapter matrix (\`cargo test -p layer36-runtime uapi_dispatch::tests::dispatcher_denies_all_non_default_boundaries_before_adapter -- --exact\`) | $DISPATCHER_CODE | $(result_of "$DISPATCHER_CODE") |"
  echo "| Cat denies missing fs grant (\`cargo test -p layer36-cli --test cli configured_layer36_cat_component_denies_missing_file_grant -- --exact\`) | $CAT_CODE | $(result_of "$CAT_CODE") |"
  echo "| Curl denies missing net grant (\`cargo test -p layer36-cli --test cli configured_layer36_curl_component_denies_missing_net_grant -- --exact\`) | $CURL_CODE | $(result_of "$CURL_CODE") |"
  echo "| Manifest denies missing required cap (\`cargo test -p layer36-cli --test cli run_with_manifest_denies_missing_required_capability -- --exact\`) | $MANIFEST_CODE | $(result_of "$MANIFEST_CODE") |"
  echo "| Curl denial parity across Rust Go TS (\`cargo test -p layer36-cli --test cli language_variants_curl_permission_denied_matches_rust_go_ts -- --exact\`) | $LANGUAGE_CODE | $(result_of "$LANGUAGE_CODE") |"
  echo
  echo "## Runtime UCap deny matrix log (tail)"
  echo
  echo '```text'
  tail -n 120 "$RUNTIME_LOG"
  echo '```'
  echo
  echo "## Dispatcher deny-before-adapter matrix log (tail)"
  echo
  echo '```text'
  tail -n 120 "$DISPATCHER_LOG"
  echo '```'
  echo
  echo "## Cat deny log (tail)"
  echo
  echo '```text'
  tail -n 120 "$CAT_LOG"
  echo '```'
  echo
  echo "## Curl deny log (tail)"
  echo
  echo '```text'
  tail -n 120 "$CURL_LOG"
  echo '```'
  echo
  echo "## Manifest deny log (tail)"
  echo
  echo '```text'
  tail -n 120 "$MANIFEST_LOG"
  echo '```'
  echo
  echo "## Language-variant deny parity log (tail)"
  echo
  echo '```text'
  tail -n 120 "$LANGUAGE_LOG"
  echo '```'
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && {
  [ "$RUNTIME_CODE" -ne 0 ] ||
  [ "$DISPATCHER_CODE" -ne 0 ] ||
  [ "$CAT_CODE" -ne 0 ] ||
  [ "$CURL_CODE" -ne 0 ] ||
  [ "$MANIFEST_CODE" -ne 0 ] ||
  [ "$LANGUAGE_CODE" -ne 0 ];
}; then
  exit 1
fi

exit 0
