#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-rust-sdk-evidence/rust-sdk-evidence.md"
STRICT="${LAYER36_RUST_SDK_EVIDENCE_STRICT:-0}"
CHECK_DOCS="${LAYER36_RUST_SDK_EVIDENCE_CHECK_DOCS:-1}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-rust-sdk-evidence.sh [--strict] [--skip-docs] [--output <path>]

Options:
  --strict         Exit non-zero when any evidence step fails
  --skip-docs      Skip cargo doc check
  --output <path>  Output markdown file path

Environment:
  LAYER36_RUST_SDK_EVIDENCE_STRICT      1 to exit non-zero when any step fails
  LAYER36_RUST_SDK_EVIDENCE_CHECK_DOCS  0 to skip cargo doc check
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --skip-docs)
      CHECK_DOCS="0"
      shift
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-rust-sdk-evidence/rust-sdk-evidence.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-rust-sdk-evidence/.tmp"
mkdir -p "$TMP_DIR"
SMOKE_LOG="$TMP_DIR/smoke.log"
DOCS_LOG="$TMP_DIR/docs.log"

if scripts/smoke-rust-sdk.sh >"$SMOKE_LOG" 2>&1; then
  SMOKE_CODE=0
else
  SMOKE_CODE=$?
fi

if [ "$CHECK_DOCS" = "1" ]; then
  if cargo doc -p layer36 --no-deps >"$DOCS_LOG" 2>&1; then
    DOCS_CODE=0
  else
    DOCS_CODE=$?
  fi
else
  DOCS_CODE=0
  printf 'cargo doc check skipped (--skip-docs)\n' >"$DOCS_LOG"
fi

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
package_dir="$(
  find "$ROOT/target/package" -maxdepth 1 -type d -name 'layer36-*' 2>/dev/null \
    | sort \
    | tail -n 1
)"

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  else
    printf 'failed'
  fi
}

exists_of() {
  path="$1"
  if [ -f "$path" ]; then
    printf 'yes'
  else
    printf 'no'
  fi
}

{
  echo "# Phase 2 Rust SDK Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-rust-sdk-evidence.sh\`."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo "- Package directory: \`${package_dir:-n/a}\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| Rust SDK package smoke (\`scripts/smoke-rust-sdk.sh\`) | $SMOKE_CODE | $(result_of "$SMOKE_CODE") |"
  echo "| Rust SDK docs (\`cargo doc -p layer36 --no-deps\`) | $DOCS_CODE | $(result_of "$DOCS_CODE") |"
  echo
  echo "## Packaged Files"
  echo
  echo "| File | Exists |"
  echo "|---|---|"
  if [ -n "$package_dir" ]; then
    echo "| Cargo.toml | $(exists_of "$package_dir/Cargo.toml") |"
    echo "| README.md | $(exists_of "$package_dir/README.md") |"
    echo "| src/lib.rs | $(exists_of "$package_dir/src/lib.rs") |"
    echo "| src/bindings.rs | $(exists_of "$package_dir/src/bindings.rs") |"
  else
    echo "| Cargo.toml | no |"
    echo "| README.md | no |"
    echo "| src/lib.rs | no |"
    echo "| src/bindings.rs | no |"
  fi
  echo
  echo "## Smoke Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$SMOKE_LOG"
  echo '```'
  echo
  echo "## Docs Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$DOCS_LOG"
  echo '```'
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && { [ "$SMOKE_CODE" -ne 0 ] || [ "$DOCS_CODE" -ne 0 ]; }; then
  exit 1
fi

exit 0
