#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-adapter-evidence/adapter-evidence.md"
STRICT="${LAYER36_ADAPTER_EVIDENCE_STRICT:-0}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-adapter-evidence.sh [--strict] [--output <path>]

Options:
  --strict         Exit non-zero when adapter boundary check fails
  --output <path>  Output markdown file path

Environment:
  LAYER36_ADAPTER_EVIDENCE_STRICT   1 to exit non-zero when check fails
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-adapter-evidence/adapter-evidence.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-adapter-evidence/.tmp"
mkdir -p "$TMP_DIR"
CHECK_LOG="$TMP_DIR/check.log"

if scripts/check-adapter-boundary.sh >"$CHECK_LOG" 2>&1; then
  CHECK_CODE=0
else
  CHECK_CODE=$?
fi

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  else
    printf 'failed'
  fi
}

{
  echo "# Phase 2 Adapter Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-adapter-evidence.sh\`."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| Adapter boundary check (\`scripts/check-adapter-boundary.sh\`) | $CHECK_CODE | $(result_of "$CHECK_CODE") |"
  echo
  echo "## Adapter Boundary Check Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$CHECK_LOG"
  echo '```'
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && [ "$CHECK_CODE" -ne 0 ]; then
  exit 1
fi

exit 0
