#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-language-variant-evidence/language-variant-evidence.md"
STRICT="${LAYER36_LANGUAGE_VARIANT_EVIDENCE_STRICT:-0}"
MODE="${LAYER36_LANGUAGE_VARIANTS_MODE:-optional}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-language-variant-evidence.sh [--strict] [--mode <mode>] [--output <path>]

Options:
  --strict           Exit non-zero when build/test fails
  --mode <mode>      optional|any|both|go|ts (default: env LAYER36_LANGUAGE_VARIANTS_MODE or optional)
  --output <path>    Output markdown file path

Environment:
  LAYER36_LANGUAGE_VARIANTS_MODE             optional|any|both|go|ts (default: optional)
  LAYER36_LANGUAGE_VARIANT_EVIDENCE_STRICT   1 to exit non-zero when build/test fails

Notes:
  - The script always writes a markdown report.
  - In strict mode, it returns a non-zero exit code when build/test fails.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --mode)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --mode" >&2
        usage
        exit 2
      fi
      MODE="$2"
      shift 2
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-language-variant-evidence/language-variant-evidence.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-language-variant-evidence/.tmp"
mkdir -p "$TMP_DIR"
BUILD_LOG="$TMP_DIR/build.log"
TEST_LOG="$TMP_DIR/test.log"

if scripts/build-phase2-language-variant-fixtures.sh >"$BUILD_LOG" 2>&1; then
  BUILD_CODE=0
else
  BUILD_CODE=$?
fi

if scripts/test-phase2-language-variants.sh >"$TEST_LOG" 2>&1; then
  TEST_CODE=0
else
  TEST_CODE=$?
fi

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"

hash_of() {
  path="$1"
  if [ -f "$path" ]; then
    if command -v sha256sum >/dev/null 2>&1; then
      sha256sum "$path" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
      shasum -a 256 "$path" | awk '{print $1}'
    else
      printf 'n/a'
    fi
  else
    printf 'n/a'
  fi
}

exists_of() {
  path="$1"
  if [ -f "$path" ]; then
    printf 'yes'
  else
    printf 'no'
  fi
}

go_clock="$ROOT/test/integration/language-variants/layer36_go_clock.wasm"
go_cat="$ROOT/test/integration/language-variants/layer36_go_cat.wasm"
go_curl="$ROOT/test/integration/language-variants/layer36_go_curl.wasm"
ts_clock="$ROOT/test/integration/language-variants/layer36_ts_clock.wasm"
ts_cat="$ROOT/test/integration/language-variants/layer36_ts_cat.wasm"
ts_curl="$ROOT/test/integration/language-variants/layer36_ts_curl.wasm"

{
  echo "# Phase 2 Language Variant Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-language-variant-evidence.sh\`."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo "- Fixture mode: \`$MODE\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| Build language fixtures (\`scripts/build-phase2-language-variant-fixtures.sh\`) | $BUILD_CODE | $( [ "$BUILD_CODE" -eq 0 ] && printf 'passed' || printf 'failed' ) |"
  echo "| Test language variants (\`scripts/test-phase2-language-variants.sh\`) | $TEST_CODE | $( [ "$TEST_CODE" -eq 0 ] && printf 'passed' || printf 'failed' ) |"
  echo
  echo "## Fixture Files"
  echo
  echo "| Fixture | Exists | SHA-256 |"
  echo "|---|---|---|"
  echo "| layer36_go_clock.wasm | $(exists_of "$go_clock") | \`$(hash_of "$go_clock")\` |"
  echo "| layer36_go_cat.wasm | $(exists_of "$go_cat") | \`$(hash_of "$go_cat")\` |"
  echo "| layer36_go_curl.wasm | $(exists_of "$go_curl") | \`$(hash_of "$go_curl")\` |"
  echo "| layer36_ts_clock.wasm | $(exists_of "$ts_clock") | \`$(hash_of "$ts_clock")\` |"
  echo "| layer36_ts_cat.wasm | $(exists_of "$ts_cat") | \`$(hash_of "$ts_cat")\` |"
  echo "| layer36_ts_curl.wasm | $(exists_of "$ts_curl") | \`$(hash_of "$ts_curl")\` |"
  echo
  echo "## Build Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$BUILD_LOG"
  echo '```'
  echo
  echo "## Test Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$TEST_LOG"
  echo '```'
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && { [ "$BUILD_CODE" -ne 0 ] || [ "$TEST_CODE" -ne 0 ]; }; then
  exit 1
fi

exit 0
