#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

export PATH="$HOME/.cargo/bin:$PATH"

OUTPUT="target/phase2-fuzz-evidence/fuzz-evidence.md"
STRICT="${LAYER36_FUZZ_EVIDENCE_STRICT:-0}"
DRY_RUN="${LAYER36_FUZZ_EVIDENCE_DRY_RUN:-0}"
FUZZ_MAX_TOTAL_TIME="${LAYER36_FUZZ_MAX_TOTAL_TIME:-30}"
FUZZ_TARGETS="${LAYER36_FUZZ_TARGETS:-manifest_parse logical_path_parse policy_match}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-fuzz-evidence.sh [--strict] [--dry-run] [--max-total-time <seconds>] [--targets <space-separated-targets>] [--output <path>]

Options:
  --strict                    Exit non-zero when the fuzz smoke command fails
  --dry-run                   Record the planned cargo-fuzz commands without running them
  --max-total-time <seconds>  Seconds per fuzz target (default: 30)
  --targets <targets>         Space-separated target list
  --output <path>             Output markdown report path

Environment:
  LAYER36_FUZZ_EVIDENCE_STRICT    1 to exit non-zero when fuzz smoke fails
  LAYER36_FUZZ_EVIDENCE_DRY_RUN   1 to record planned commands only
  LAYER36_FUZZ_MAX_TOTAL_TIME     Seconds per fuzz target
  LAYER36_FUZZ_TARGETS            Space-separated target list
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --dry-run)
      DRY_RUN="1"
      shift
      ;;
    --max-total-time)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --max-total-time" >&2
        usage
        exit 2
      fi
      FUZZ_MAX_TOTAL_TIME="$2"
      shift 2
      ;;
    --targets)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --targets" >&2
        usage
        exit 2
      fi
      FUZZ_TARGETS="$2"
      shift 2
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-fuzz-evidence/fuzz-evidence.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

case "$FUZZ_MAX_TOTAL_TIME" in
  ''|*[!0-9]*)
    echo "Fuzz evidence error: --max-total-time must be a positive integer" >&2
    exit 2
    ;;
esac

if [ "$FUZZ_MAX_TOTAL_TIME" -lt 1 ]; then
  echo "Fuzz evidence error: --max-total-time must be at least 1" >&2
  exit 2
fi

if [ -z "$FUZZ_TARGETS" ]; then
  echo "Fuzz evidence error: target list must not be empty" >&2
  exit 2
fi

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="$(dirname "$OUTPUT")/.tmp-$(basename "$OUTPUT")"
mkdir -p "$TMP_DIR"

FUZZ_LOG="$TMP_DIR/fuzz-smoke.log"

if LAYER36_FUZZ_MAX_TOTAL_TIME="$FUZZ_MAX_TOTAL_TIME" \
  LAYER36_FUZZ_TARGETS="$FUZZ_TARGETS" \
  LAYER36_FUZZ_SMOKE_DRY_RUN="$DRY_RUN" \
  scripts/run-phase2-fuzz-smoke.sh >"$FUZZ_LOG" 2>&1; then
  FUZZ_CODE=0
else
  FUZZ_CODE=$?
fi

version_of() {
  tool="$1"
  if command -v "$tool" >/dev/null 2>&1; then
    "$tool" --version 2>/dev/null | head -n 1
  else
    printf 'not found'
  fi
}

rustup_nightly() {
  if command -v rustup >/dev/null 2>&1 && rustup toolchain list 2>/dev/null | grep -q "^nightly"; then
    rustup which --toolchain nightly rustc 2>/dev/null || printf 'nightly installed'
  else
    printf 'not found'
  fi
}

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  else
    printf 'failed'
  fi
}

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"

{
  echo "# Phase 2 Fuzz Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-fuzz-evidence.sh\`."
  echo
  echo "It records a fuzz smoke or soak run for Phase 2 review. It is evidence,"
  echo "not a completion stamp."
  echo
  echo "## Scope"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo "- Targets: \`$FUZZ_TARGETS\`"
  echo "- Seconds per target: \`$FUZZ_MAX_TOTAL_TIME\`"
  echo "- Dry run: \`$DRY_RUN\`"
  echo "- Strict mode: \`$STRICT\`"
  echo
  echo "## Tooling"
  echo
  echo "- cargo-fuzz: \`$(version_of cargo-fuzz)\`"
  echo "- rustup: \`$(version_of rustup)\`"
  echo "- nightly rustc: \`$(rustup_nightly)\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| Fuzz smoke (\`scripts/run-phase2-fuzz-smoke.sh\`) | $FUZZ_CODE | $(result_of "$FUZZ_CODE") |"
  echo
  echo "## Fuzz Log Tail"
  echo
  echo '```text'
  tail -n 160 "$FUZZ_LOG"
  echo '```'
  echo
  echo "## Reading This Report"
  echo
  echo "For final Phase 2 exit, use a fresh report from the final candidate commit."
  echo "A short smoke run is useful for local review. A longer self-hosted soak should"
  echo "use the same recorder with a larger \`--max-total-time\` value."
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && [ "$FUZZ_CODE" -ne 0 ]; then
  exit 1
fi

exit 0
