#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-dependency-evidence/dependency-evidence.md"
STRICT="${LAYER36_DEPENDENCY_EVIDENCE_STRICT:-0}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-dependency-evidence.sh [--strict] [--output <path>]

Options:
  --strict        Exit non-zero when the dependency check fails
  --output <md>   Output markdown file path

Environment:
  LAYER36_DEPENDENCY_EVIDENCE_STRICT  1 to exit non-zero when the dependency check fails
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-dependency-evidence/dependency-evidence.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-dependency-evidence/.tmp"
mkdir -p "$TMP_DIR"

DEPENDENCY_LOG="$TMP_DIR/check-dependencies.log"
TOOL_LOG="$TMP_DIR/tools.log"

if scripts/check-dependencies.sh >"$DEPENDENCY_LOG" 2>&1; then
  DEPENDENCY_CODE=0
else
  DEPENDENCY_CODE=$?
fi

{
  cargo deny --version 2>/dev/null || true
  cargo --version 2>/dev/null || true
  rustc --version 2>/dev/null || true
} >"$TOOL_LOG"

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  else
    printf 'failed'
  fi
}

advisory_status="checked"
if grep -Eq "advisory check skipped|failed to acquire advisory database lock|unsupported CVSS version|failed to load advisory database|TOML parse error" "$DEPENDENCY_LOG"; then
  advisory_status="skipped-with-warning"
fi

license_bans_sources_status="unknown"
if grep -q "bans ok, licenses ok, sources ok" "$DEPENDENCY_LOG"; then
  license_bans_sources_status="passed"
elif [ "$DEPENDENCY_CODE" -ne 0 ]; then
  license_bans_sources_status="failed"
fi

{
  echo "# Phase 2 Dependency Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-dependency-evidence.sh\`."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo
  echo "## Result"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| Dependency audit (\`scripts/check-dependencies.sh\`) | $DEPENDENCY_CODE | $(result_of "$DEPENDENCY_CODE") |"
  echo
  echo "## Audit Shape"
  echo
  echo "| Check | Status |"
  echo "|---|---|"
  echo "| Advisories | \`$advisory_status\` |"
  echo "| Licenses, bans, sources | \`$license_bans_sources_status\` |"
  echo
  echo "## Tool Versions"
  echo
  echo '```text'
  cat "$TOOL_LOG"
  echo '```'
  echo
  echo "## Dependency Check Log (tail)"
  echo
  echo '```text'
  tail -n 160 "$DEPENDENCY_LOG"
  echo '```'
  echo
  echo "## Reading The Result"
  echo
  echo "For Phase 2 exit, this report should show a passing dependency audit on the same commit used for the final sample and benchmark reports. If the advisory check is skipped because of a local advisory database lock or a temporary cargo-deny parser issue, the report should say that clearly and the hosted audit should be checked before final signoff."
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && [ "$DEPENDENCY_CODE" -ne 0 ]; then
  exit 1
fi

exit 0
