#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-walkthrough/walkthrough-template.md"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-walkthrough-template.sh [--output <path>]

Options:
  --output <md>   Output markdown file path
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-walkthrough/walkthrough-template.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"

{
  echo "# Phase 2 Timed Walkthrough Evidence Template"
  echo
  echo "This file is generated by \`scripts/record-phase2-walkthrough-template.sh\`."
  echo
  echo "Use it with [Your First UAPI App In Rust](docs/book/src/uapi/first-rust-cli.md)."
  echo "The reviewer should start a timer before step 1 and stop it after the denial"
  echo "path in step 7 succeeds."
  echo
  echo "## Run Metadata"
  echo
  echo "- Git commit under review: \`$git_commit\`"
  echo "- Template generated at (UTC): \`$now_utc\`"
  echo "- Host used to generate template: \`$host_os\` / \`$host_arch\`"
  echo "- Reviewer name or handle:"
  echo "- Reviewer background:"
  echo "- Review host OS and arch:"
  echo "- Started at:"
  echo "- Finished at:"
  echo "- Total minutes:"
  echo "- Result: pass / fail"
  echo
  echo "## Pass Rule"
  echo
  echo "P2E-12 passes when a Rust developer who does not already know Layer36 can"
  echo "complete the Rust UAPI walkthrough in 30 minutes or less without private help."
  echo
  echo "## Step Results"
  echo
  echo "| Step | Expected result | Reviewer result | Notes |"
  echo "|---|---|---|---|"
  echo "| Tool check | \`layer36 doctor\` shows required Rust tooling or clear install guidance |  |  |"
  echo "| Build CLI | \`cargo build -p layer36-cli\` passes |  |  |"
  echo "| Build cat component | \`scripts/build-layer36-cat-component.sh\` prints a wasm path |  |  |"
  echo "| Generate manifest | \`manifest.toml\` is written and capabilities parse |  |  |"
  echo "| Explain manifest | reviewer can identify default grants and explicit fs grant |  |  |"
  echo "| Granted run | app prints \`hello from Layer36\` |  |  |"
  echo "| Denied run | app exits before native file access with a missing-capability message |  |  |"
  echo
  echo "## Reviewer Notes"
  echo
  echo "- What was confusing?"
  echo "- What command failed first, if any?"
  echo "- What wording should be clearer?"
  echo "- Would this be usable without the repo author present?"
  echo
  echo "## Evidence To Attach"
  echo
  echo "Paste the final terminal transcript or attach the saved log. Keep secrets out"
  echo "of the transcript."
} >"$OUTPUT"

echo "wrote $OUTPUT"
