#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-exit-bundle/exit-bundle.md"
STRICT="${LAYER36_EXIT_BUNDLE_STRICT:-0}"
INCLUDE_RUST_SDK="${LAYER36_EXIT_BUNDLE_INCLUDE_RUST_SDK:-0}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-exit-bundle.sh [--strict] [--include-rust-sdk] [--output <path>]

Options:
  --strict            Exit non-zero when any included evidence step fails
  --include-rust-sdk  Also run the Rust SDK package evidence recorder
  --output <path>     Output markdown file path

Environment:
  LAYER36_EXIT_BUNDLE_STRICT            1 to exit non-zero on failed included steps
  LAYER36_EXIT_BUNDLE_INCLUDE_RUST_SDK  1 to include Rust SDK package evidence
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --include-rust-sdk)
      INCLUDE_RUST_SDK="1"
      shift
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-exit-bundle/exit-bundle.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-exit-bundle/.tmp"
mkdir -p "$TMP_DIR"

UAPI_LOG="$TMP_DIR/check-uapi.log"
FREEZE_LOCK_LOG="$TMP_DIR/check-uapi-freeze-lock.log"
ADAPTER_LOG="$TMP_DIR/check-adapter-boundary.log"
EXIT_LEDGER_LOG="$TMP_DIR/check-phase2-exit-evidence.log"
DOCS_LOG="$TMP_DIR/mdbook.log"
DEPENDENCY_LOG="$TMP_DIR/dependency-evidence.log"
DEPENDENCY_REPORT="$TMP_DIR/dependency-evidence.md"
SDK_LOG="$TMP_DIR/rust-sdk-evidence.log"
SDK_REPORT="$TMP_DIR/rust-sdk-evidence.md"

if scripts/check-uapi.sh >"$UAPI_LOG" 2>&1; then
  UAPI_CODE=0
else
  UAPI_CODE=$?
fi

if scripts/check-uapi-freeze-lock.sh >"$FREEZE_LOCK_LOG" 2>&1; then
  FREEZE_LOCK_CODE=0
else
  FREEZE_LOCK_CODE=$?
fi

if scripts/check-adapter-boundary.sh >"$ADAPTER_LOG" 2>&1; then
  ADAPTER_CODE=0
else
  ADAPTER_CODE=$?
fi

if scripts/check-phase2-exit-evidence.sh >"$EXIT_LEDGER_LOG" 2>&1; then
  EXIT_LEDGER_CODE=0
else
  EXIT_LEDGER_CODE=$?
fi

if command -v mdbook >/dev/null 2>&1; then
  MDBOOK="mdbook"
elif [ -x "$HOME/.cargo/bin/mdbook" ]; then
  MDBOOK="$HOME/.cargo/bin/mdbook"
else
  MDBOOK=""
fi

if [ -n "$MDBOOK" ]; then
  if "$MDBOOK" build docs/book >"$DOCS_LOG" 2>&1; then
    DOCS_CODE=0
  else
    DOCS_CODE=$?
  fi
else
  DOCS_CODE=127
  printf 'mdbook not found in PATH or $HOME/.cargo/bin\n' >"$DOCS_LOG"
fi

if scripts/record-phase2-dependency-evidence.sh --strict --output "$DEPENDENCY_REPORT" >"$DEPENDENCY_LOG" 2>&1; then
  DEPENDENCY_CODE=0
else
  DEPENDENCY_CODE=$?
fi

if [ "$INCLUDE_RUST_SDK" = "1" ]; then
  if scripts/record-phase2-rust-sdk-evidence.sh --strict --output "$SDK_REPORT" >"$SDK_LOG" 2>&1; then
    SDK_CODE=0
  else
    SDK_CODE=$?
  fi
else
  SDK_CODE=0
  printf 'Rust SDK package evidence skipped. Run with --include-rust-sdk to include it.\n' >"$SDK_LOG"
fi

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
git_status="$(git status --short 2>/dev/null || true)"

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  else
    printf 'failed'
  fi
}

included_of() {
  flag="$1"
  if [ "$flag" = "1" ]; then
    printf 'yes'
  else
    printf 'no'
  fi
}

{
  echo "# Phase 2 Exit Bundle"
  echo
  echo "This file is generated by \`scripts/record-phase2-exit-bundle.sh\`."
  echo
  echo "It is a local review bundle, not a Phase 2 completion stamp. It collects"
  echo "the cheap checks that should be green before a final exit review."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo "- Rust SDK package evidence included: \`$(included_of "$INCLUDE_RUST_SDK")\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| UAPI contract check (\`scripts/check-uapi.sh\`) | $UAPI_CODE | $(result_of "$UAPI_CODE") |"
  echo "| UAPI freeze lock check (\`scripts/check-uapi-freeze-lock.sh\`) | $FREEZE_LOCK_CODE | $(result_of "$FREEZE_LOCK_CODE") |"
  echo "| Adapter boundary check (\`scripts/check-adapter-boundary.sh\`) | $ADAPTER_CODE | $(result_of "$ADAPTER_CODE") |"
  echo "| Exit ledger check (\`scripts/check-phase2-exit-evidence.sh\`) | $EXIT_LEDGER_CODE | $(result_of "$EXIT_LEDGER_CODE") |"
  echo "| Docs build (\`mdbook build docs/book\`) | $DOCS_CODE | $(result_of "$DOCS_CODE") |"
  echo "| Dependency evidence (\`scripts/record-phase2-dependency-evidence.sh --strict\`) | $DEPENDENCY_CODE | $(result_of "$DEPENDENCY_CODE") |"
  if [ "$INCLUDE_RUST_SDK" = "1" ]; then
    echo "| Rust SDK evidence (\`scripts/record-phase2-rust-sdk-evidence.sh --strict\`) | $SDK_CODE | $(result_of "$SDK_CODE") |"
  else
    echo "| Rust SDK evidence | 0 | skipped |"
  fi
  echo
  echo "## Gate Snapshot"
  echo
  echo "Current gate states are copied from \`docs/book/src/phase2/exit-evidence.md\`:"
  echo
  echo "| Gate | Criterion | Status |"
  echo "|---|---|---|"
  awk -F '|' '/^\| P2E-/ {
    gate=$2
    criterion=$3
    status=$4
    gsub(/^ +| +$/, "", gate)
    gsub(/^ +| +$/, "", criterion)
    gsub(/^ +| +$/, "", status)
    printf "| %s | %s | %s |\n", gate, criterion, status
  }' docs/book/src/phase2/exit-evidence.md
  echo
  echo "## Working Tree"
  echo
  if [ -n "$git_status" ]; then
    echo '```text'
    printf '%s\n' "$git_status"
    echo '```'
  else
    echo "Clean at generation time."
  fi
  echo
  echo "## UAPI Check Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$UAPI_LOG"
  echo '```'
  echo
  echo "## UAPI Freeze Lock Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$FREEZE_LOCK_LOG"
  echo '```'
  echo
  echo "## Adapter Boundary Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$ADAPTER_LOG"
  echo '```'
  echo
  echo "## Exit Ledger Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$EXIT_LEDGER_LOG"
  echo '```'
  echo
  echo "## Docs Build Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$DOCS_LOG"
  echo '```'
  echo
  echo "## Dependency Evidence Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$DEPENDENCY_LOG"
  echo '```'
  if [ -f "$DEPENDENCY_REPORT" ]; then
    echo
    echo "## Dependency Evidence Summary"
    echo
    sed -n '1,42p' "$DEPENDENCY_REPORT"
  fi
  echo
  echo "## Rust SDK Evidence Log (tail)"
  echo
  echo '```text'
  tail -n 120 "$SDK_LOG"
  echo '```'
  if [ "$INCLUDE_RUST_SDK" = "1" ] && [ -f "$SDK_REPORT" ]; then
    echo
    echo "## Rust SDK Evidence Summary"
    echo
    sed -n '1,40p' "$SDK_REPORT"
  fi
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && {
  [ "$UAPI_CODE" -ne 0 ] ||
  [ "$FREEZE_LOCK_CODE" -ne 0 ] ||
  [ "$ADAPTER_CODE" -ne 0 ] ||
  [ "$EXIT_LEDGER_CODE" -ne 0 ] ||
  [ "$DOCS_CODE" -ne 0 ] ||
  [ "$DEPENDENCY_CODE" -ne 0 ] ||
  [ "$SDK_CODE" -ne 0 ];
}; then
  exit 1
fi

exit 0
