#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-uapi-freeze-review/uapi-freeze-review.md"
STRICT="${LAYER36_UAPI_FREEZE_REVIEW_STRICT:-0}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-uapi-freeze-review.sh [--strict] [--output <path>]

Options:
  --strict        Exit non-zero when any review step fails
  --output <md>   Output markdown file path

Environment:
  LAYER36_UAPI_FREEZE_REVIEW_STRICT  1 to exit non-zero when any review step fails
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-uapi-freeze-review/uapi-freeze-review.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-uapi-freeze-review/.tmp"
mkdir -p "$TMP_DIR"

UAPI_LOG="$TMP_DIR/check-uapi.log"
REFERENCE_LOG="$TMP_DIR/generate-uapi-reference.log"
REFERENCE_DIFF_LOG="$TMP_DIR/uapi-reference-diff.log"
FREEZE_EVIDENCE_LOG="$TMP_DIR/generate-uapi-freeze-evidence.log"
FREEZE_EVIDENCE_DIFF_LOG="$TMP_DIR/uapi-freeze-evidence-diff.log"
FREEZE_LOCK_LOG="$TMP_DIR/generate-uapi-freeze-lock.log"
FREEZE_LOCK_DIFF_LOG="$TMP_DIR/uapi-freeze-lock-diff.log"
FREEZE_LOCK_CHECK_LOG="$TMP_DIR/check-uapi-freeze-lock.log"
ADAPTER_LOG="$TMP_DIR/check-adapter-boundary.log"
EXIT_LEDGER_LOG="$TMP_DIR/check-phase2-exit-evidence.log"

if scripts/check-uapi.sh >"$UAPI_LOG" 2>&1; then
  UAPI_CODE=0
else
  UAPI_CODE=$?
fi

if scripts/generate-uapi-reference.sh >"$REFERENCE_LOG" 2>&1; then
  REFERENCE_CODE=0
else
  REFERENCE_CODE=$?
fi

if git diff --exit-code -- docs/book/src/reference/uapi/index.md >"$REFERENCE_DIFF_LOG" 2>&1; then
  REFERENCE_DIFF_CODE=0
else
  REFERENCE_DIFF_CODE=$?
fi

if scripts/generate-uapi-freeze-evidence.sh >"$FREEZE_EVIDENCE_LOG" 2>&1; then
  FREEZE_EVIDENCE_CODE=0
else
  FREEZE_EVIDENCE_CODE=$?
fi

if git diff --exit-code -- docs/book/src/phase2/uapi-freeze-evidence.md >"$FREEZE_EVIDENCE_DIFF_LOG" 2>&1; then
  FREEZE_EVIDENCE_DIFF_CODE=0
else
  FREEZE_EVIDENCE_DIFF_CODE=$?
fi

if scripts/generate-uapi-freeze-lock.sh >"$FREEZE_LOCK_LOG" 2>&1; then
  FREEZE_LOCK_CODE=0
else
  FREEZE_LOCK_CODE=$?
fi

if git diff --exit-code -- docs/book/src/phase2/uapi-freeze-lock.md >"$FREEZE_LOCK_DIFF_LOG" 2>&1; then
  FREEZE_LOCK_DIFF_CODE=0
else
  FREEZE_LOCK_DIFF_CODE=$?
fi

if scripts/check-uapi-freeze-lock.sh >"$FREEZE_LOCK_CHECK_LOG" 2>&1; then
  FREEZE_LOCK_CHECK_CODE=0
else
  FREEZE_LOCK_CHECK_CODE=$?
fi

if scripts/check-adapter-boundary.sh >"$ADAPTER_LOG" 2>&1; then
  ADAPTER_CODE=0
else
  ADAPTER_CODE=$?
fi

if scripts/check-phase2-exit-evidence.sh >"$EXIT_LEDGER_LOG" 2>&1; then
  EXIT_LEDGER_CODE=0
else
  EXIT_LEDGER_CODE=$?
fi

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
git_status="$(git status --short 2>/dev/null || true)"

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  else
    printf 'failed'
  fi
}

overall_result="candidate evidence is current"
if [ "$UAPI_CODE" -ne 0 ] ||
  [ "$REFERENCE_CODE" -ne 0 ] ||
  [ "$REFERENCE_DIFF_CODE" -ne 0 ] ||
  [ "$FREEZE_EVIDENCE_CODE" -ne 0 ] ||
  [ "$FREEZE_EVIDENCE_DIFF_CODE" -ne 0 ] ||
  [ "$FREEZE_LOCK_CODE" -ne 0 ] ||
  [ "$FREEZE_LOCK_DIFF_CODE" -ne 0 ] ||
  [ "$FREEZE_LOCK_CHECK_CODE" -ne 0 ] ||
  [ "$ADAPTER_CODE" -ne 0 ] ||
  [ "$EXIT_LEDGER_CODE" -ne 0 ]; then
  overall_result="needs review before freeze"
fi

{
  echo "# Phase 2 UAPI Freeze Review Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-uapi-freeze-review.sh\`."
  echo
  echo "It checks whether the current UAPI freeze candidate is internally consistent."
  echo "It does not make the final freeze decision."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo "- Result: \`$overall_result\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| UAPI contract check (\`scripts/check-uapi.sh\`) | $UAPI_CODE | $(result_of "$UAPI_CODE") |"
  echo "| Regenerate UAPI reference | $REFERENCE_CODE | $(result_of "$REFERENCE_CODE") |"
  echo "| UAPI reference freshness | $REFERENCE_DIFF_CODE | $(result_of "$REFERENCE_DIFF_CODE") |"
  echo "| Regenerate freeze evidence | $FREEZE_EVIDENCE_CODE | $(result_of "$FREEZE_EVIDENCE_CODE") |"
  echo "| Freeze evidence freshness | $FREEZE_EVIDENCE_DIFF_CODE | $(result_of "$FREEZE_EVIDENCE_DIFF_CODE") |"
  echo "| Regenerate freeze lock | $FREEZE_LOCK_CODE | $(result_of "$FREEZE_LOCK_CODE") |"
  echo "| Freeze lock freshness | $FREEZE_LOCK_DIFF_CODE | $(result_of "$FREEZE_LOCK_DIFF_CODE") |"
  echo "| Freeze lock checker | $FREEZE_LOCK_CHECK_CODE | $(result_of "$FREEZE_LOCK_CHECK_CODE") |"
  echo "| Adapter boundary guard | $ADAPTER_CODE | $(result_of "$ADAPTER_CODE") |"
  echo "| Phase 2 exit ledger guard | $EXIT_LEDGER_CODE | $(result_of "$EXIT_LEDGER_CODE") |"
  echo
  echo "## Reading This Report"
  echo
  echo "A passing report means the current WIT, generated reference, freeze evidence,"
  echo "freeze lock, adapter-boundary guard, and exit ledger agree with each other."
  echo "The final Phase 2 freeze still needs the remaining cross-host and language"
  echo "evidence listed in the exit ledger."
  echo
  echo "## Current Freeze Lock Summary"
  echo
  sed -n '/^## Summary/,/^## Files/p' docs/book/src/phase2/uapi-freeze-lock.md | sed '$d'
  echo
  echo "## Relevant Exit Gates"
  echo
  echo
  echo "| Gate | Criterion | Status |"
  echo "|---|---|---|"
  awk -F '|' '/^\| P2E-(01|02|03|04|05|09|13|14|15)/ {
    gate=$2
    criterion=$3
    status=$4
    gsub(/^ +| +$/, "", gate)
    gsub(/^ +| +$/, "", criterion)
    gsub(/^ +| +$/, "", status)
    printf "| %s | %s | %s |\n", gate, criterion, status
  }' docs/book/src/phase2/exit-evidence.md
  echo
  echo "## Working Tree"
  echo
  if [ -n "$git_status" ]; then
    echo '```text'
    printf '%s\n' "$git_status"
    echo '```'
  else
    echo "Clean at generation time."
  fi
  echo
  echo "## Log Tails"
  echo
  for entry in \
    "UAPI check:$UAPI_LOG" \
    "UAPI reference:$REFERENCE_LOG" \
    "UAPI reference diff:$REFERENCE_DIFF_LOG" \
    "Freeze evidence:$FREEZE_EVIDENCE_LOG" \
    "Freeze evidence diff:$FREEZE_EVIDENCE_DIFF_LOG" \
    "Freeze lock:$FREEZE_LOCK_LOG" \
    "Freeze lock diff:$FREEZE_LOCK_DIFF_LOG" \
    "Freeze lock check:$FREEZE_LOCK_CHECK_LOG" \
    "Adapter boundary:$ADAPTER_LOG" \
    "Exit ledger:$EXIT_LEDGER_LOG"
  do
    label="${entry%%:*}"
    path="${entry#*:}"
    echo
    echo "### $label"
    echo
    echo '```text'
    tail -n 80 "$path"
    echo '```'
  done
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && [ "$overall_result" != "candidate evidence is current" ]; then
  exit 1
fi

exit 0
